"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
of D?
"""

def isPentagonal(n):
    num = ((24*n + 1)**0.5 + 1) / 6
    return num == int(num)

def main():
    i = 1
    notFound = True
    while notFound:
        i += 1
        n = int(i * (3 * i - 1) / 2)

        for j in range(i-1, 0, -1):
            m = int(j * (3 * j - 1) / 2)
            if (isPentagonal(n+m) and isPentagonal(n-m)):
                print(n-m)
                notFound = False
                break

if (__name__ == "__main__"):
    main()
