"""
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	        1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

#Start at the verified indexes
def triangle():
    i = 286
    while True:
        yield int(i * (i + 1) / 2)
        i += 1

def pentagonal():
    j = 166
    while True:
        yield int(j * (3*j - 1) / 2)
        j += 1

def hexagonal():
    k = 144
    while True:
        yield int(k * (2*k - 1))
        k += 1

def match(a, b, c):
    return (a == b and a == c)

T = triangle()
P = pentagonal()
H = hexagonal()

t = next(T)
p = next(P)
h = next(H)

while not match(t, p, h):
    if (t > p):
        p = next(P)

    if (p > h):
        h = next(H)

    t = next(T)

print(t, p, h)

